### ISSUE TITLE
Make --index a simple flag

### ISSUE THREAD

**Issue by dsheets** [dsheets/codoc#43]
It takes an argument right now which is confusing and has muddled semantics.

**Comment by dbuenzli** [comment]
And why should it be last on the command line ? That's not what optional arguments are for.

**Comment by dsheets** [comment]
Only because it takes an optional argument and cmdliner accepts `--index some/path` as equal to `--index=some/path` so it's easy to get confused about why you "haven't supplied a path". If it's last on the command line, this isn't a problem (or if it's just a simple flag).
