### ISSUE TITLE
Submodules: default should not include them on the same page.

### ISSUE THREAD

**Issue by dbuenzli** [dsheets/codoc#54]
I think that by default you should not include the documentation of submodules on the same page. Submodules are a natural way to chunk functionality *and* documentation in cognitively bite sized elements. All my documentation is designed around this principle, so currently it doesn't look good (in the sense you get annoyed by details you should not be annoyed with when you want to have a cusory look at the module).

Related to #4 and https://github.com/lpw25/opam-doc-base/issues/70

**Comment by dsheets** [comment]
See also #6.
