### ISSUE TITLE
Module indexes: not found errors are not useful.

### ISSUE THREAD

**Issue by dbuenzli** [dsheets/codoc#55]
I don't see any value in that collapsable arrow with Not_found errors. Maybe you could add that as a `title` attribute on where there should have been a link (this `title` will then show as a tooltip).

**Comment by dsheets** [comment]
This isn't the final design. This feature is more useful as a debugging aid. During each phase of generation (extracting, linking, and rendering), non-fatal warnings are discovered and recorded in the indexes. These warnings are then available to be rendered (or not) into the HTML. Eventually, these lint warnings will be more than simply resolution failures and our templating system will let you render them or not depending on your mood and audience.
