### ISSUE TITLE
Value signatures: labeled argument class

### ISSUE THREAD

**Issue by dbuenzli** [dsheets/codoc#56]
At the moment it seems there's no way to style (argument) labels. Besides it would be nice not to prettify the arrows so that we can easily cut and paste the definitions.

**Comment by dsheets** [comment]
The identifiers should be in spans. The cut-and-paste of arrows has been fixed in CSS (and can be reverted to ASCII arrows through removal of CSS).

**Comment by dsheets** [comment]
What do you mean by "(argument) labels"? I assumed you mean signature identifiers but I realize now that's probably wrong.

**Comment by dbuenzli** [comment]
`?bla:type -> bli:type`
