### ISSUE TITLE
Can't produce the documentation of Uucp

### ISSUE THREAD

**Issue by dbuenzli** [dsheets/codoc#58]
No documentation is produced, this error shows up:

```
XML error parsing _build/codoc/src/uucp/index.xml:56:1712 : Syntax error
```

Steps to reproduce:

```
cd /tmp
curl -O http://erratique.ch/software/uucp/releases/uucp-0.9.1.tbz
tar -xvzf  uucp-0.9.1.tbz
export OCAMLPARAM=_,doc=1,w=-50,bin-annot=1
./pkg/build.ml native=true native-dynlink=true
codoc doc _build -o _build/codoc 
```

**Comment by dsheets** [comment]
This is due to the trailing dot in that comment being interpreted as an OCaml parent identifier path separator. I've opened lpw25/doc-ock-lib#48 and lpw25/doc-ock-xml#8 to track the various issues.
