### ISSUE TITLE
Question: Why XML instead of JSON

### ISSUE THREAD

**Issue by jordwalke** [dsheets/codoc#63]
JSON seems like an easier format to manipulate and integrate into web renderers. I don't think it matters too much, but just curious what the reasoning was.

**Comment by dbuenzli** [comment]
Not speaking on behalf of the authors but for once XML is used for what it has been designed for... Why put document markup data in JSON string members when you have a format that's precisely designed to handle that ? Why deal with two data formats when you can solve the problem naturally with one ?

**Comment by dsheets** [comment]
@dbuenzli has got it. Documentation is really about marked up documents which may contain multiple different markup languages (OCaml docs, HTML, indexes, etc). We pre-render HTML and serve it directly and so avoid all JavaScript in the browser. We use `xmlm` via `cow` to render so we already have this as a dependency.

If you're interested in a JSON representation, I'm sure a JSON codec on top of `doc-ock-lib` would be useful.
