### ISSUE TITLE
Some references are not linkified

### ISSUE THREAD

**Issue by dbuenzli** [dsheets/codoc#69]
E.g. search `root:` on [this page](http://dsheets.github.io/codoc/cmdliner.0.9.6/_build/src/cmdliner/).

**Comment by dsheets** [comment]
Oops, yes, I think this is just an omission and not due to any good reason.

**Comment by dsheets** [comment]
https://github.com/lpw25/doc-ock/issues/54 should address most (if not all) of those errors.
