### ISSUE TITLE
cmt files are ignored

### ISSUE THREAD

**Issue by ivg** [dsheets/codoc#73]
It looks like that only `cmti` files are used to generate documentation with `opam doc`, and libraries like `core` that has modules that doesn't have `mli` files, but are crucial for understanding library are ignored. I'm talking about `std.ml` module, in this case.

**Comment by dsheets** [comment]
Library support for this is tracked by lpw25/doc-ock-lib#3. This issue will remain open to track codoc's integration of this support when it comes online.
