### ISSUE TITLE
Support a stand-alone indexing command

### ISSUE THREAD

**Issue by lpw25** [dsheets/codoc#79]
The current approach of creating/mutating an index as part of extracting or linking the modules within the index is slightly annoying for incremental builds. I would like to extract and link each module using a separate command invocation. If there was a stand-alone index command that took a list of modules/sub-indexes and made an index file then this would be easier.

**Comment by dsheets** [comment]
This is very similar to #44.

**Comment by lpw25** [comment]
> This is very similar to #44.

Oh yes, so it is. I'll close this one then.
