### ISSUE TITLE
Mark codoc as deprecated

### ISSUE THREAD

**Issue by yawaramin** [dsheets/codoc#98]
According to https://github.com/dsheets/codoc/issues/97#issuecomment-301159017 , codoc is now deprecated in favour of odoc (which is in development now). So I propose that we put up a notice prominently in the codoc README making readers aware of this.

If no objections, I'll be happy to send a PR.

**Comment by dsheets** [comment]
Good idea. Thanks for the suggestion and initiative! Please send a PR.
